CREATE TABLE tb_instituicao (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    CO_ENTIDADE INTEGER NOT NULL,         
    NO_ENTIDADE TEXT NOT NULL,             
    CO_UF INTEGER NOT NULL,                
    SG_UF TEXT NOT NULL,                      
    CO_MUNICIPIO INTEGER NOT NULL,         
    NO_MUNICIPIO TEXT NOT NULL,             
    CO_MESORREGIAO INTEGER NOT NULL,       
    NO_MESORREGIAO TEXT NOT NULL,           
    CO_MICRORREGIAO INTEGER NOT NULL,      
    NO_MICRORREGIAO TEXT NOT NULL,         
    QT_MAT_BAS INTEGER NOT NULL,           
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
