"""teste

Revision ID: 359dc88b432e
Revises: 
Create Date: 2025-08-11 21:54:15.421899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359dc88b432e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_UF',
    sa.Column('coduf', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('nomeestado', sa.String(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('coduf')
    )
    op.create_table('tb_Mesorregiao',
    sa.Column('codmesorregiao', sa.Integer(), nullable=False),
    sa.Column('mesorregiao', sa.String(), nullable=False),
    sa.Column('coduf', sa.Integer(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['coduf'], ['tb_UF.coduf'], ),
    sa.PrimaryKeyConstraint('codmesorregiao')
    )
    op.create_table('tb_Microrregiao',
    sa.Column('codmicrorregiao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('microrregiao', sa.String(), nullable=False),
    sa.Column('codmesorregiao', sa.Integer(), nullable=False),
    sa.Column('coduf', sa.Integer(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['codmesorregiao'], ['tb_Mesorregiao.codmesorregiao'], ),
    sa.ForeignKeyConstraint(['coduf'], ['tb_UF.coduf'], ),
    sa.PrimaryKeyConstraint('codmicrorregiao')
    )
    op.create_table('tb_Municipio',
    sa.Column('idmunicipio', sa.Integer(), nullable=False),
    sa.Column('nomemunicipio', sa.String(), nullable=False),
    sa.Column('coduf', sa.Integer(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.Column('codmesorregiao', sa.Integer(), nullable=False),
    sa.Column('codmicrorregiao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codmesorregiao'], ['tb_Mesorregiao.codmesorregiao'], ),
    sa.ForeignKeyConstraint(['codmicrorregiao'], ['tb_Microrregiao.codmicrorregiao'], ),
    sa.ForeignKeyConstraint(['coduf'], ['tb_UF.coduf'], ),
    sa.PrimaryKeyConstraint('idmunicipio')
    )
    op.create_table('tb_instituicao',
    sa.Column('regiao', sa.String(), nullable=False),
    sa.Column('codregiao', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('coduf', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('codmunicipio', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(), nullable=False),
    sa.Column('codentidade', sa.Integer(), nullable=False),
    sa.Column('matriculas_base', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['codmunicipio'], ['tb_Municipio.idmunicipio'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_instituicao')
    op.drop_table('tb_Municipio')
    op.drop_table('tb_Microrregiao')
    op.drop_table('tb_Mesorregiao')
    op.drop_table('tb_UF')
    # ### end Alembic commands ###
